# @package _global_

defaults:
  - override /hydra/sweeper: optuna

seed: 12345

data:
  batch_size: 64

trainer:
  max_epochs: 20
  accumulate_grad_batches: 4
  limit_val_batches: 0.1

#callbacks:
#  early_stopping:
#    monitor: "val/loss"
#    patience: 4
#    mode: "min"

optimized_metric: "test/loss"
hydra:
  mode: "MULTIRUN"
  sweeper:
    _target_: hydra_plugins.hydra_optuna_sweeper.optuna_sweeper.OptunaSweeper
    n_jobs: 1
    direction: minimize
    n_trials: 10
    sampler:
      _target_: optuna.samplers.TPESampler
      seed: 12345
      n_startup_trials: 4
    params:
      model.optimizer.weight_decay: interval(1e-6, 1e-3)
      model.optimizer.lr: interval(5e-4, 1e-2)
      model.lr_min: interval(1e-6, 1e-4)

