# @package _global_
defaults:
  - /loss: mse

model:
  _target_: src.models.regression_transfer.RegressionTransfer
  compile: false

  optimizer:
    _target_: torch.optim.AdamW
    _partial_: true
    lr: 0.00715
    weight_decay: 0.001973
  lr_min: 0.000345

  cls_token: false

  selector:
    _target_: torch.nn.Identity
  backbone:
    _target_: torch.nn.Identity
  head:
    _target_: torch.nn.Sequential
    _args_:
      - _target_: src.modules.vision_backbones.BlindTileEmbedder
        out_dim: 256
      - _target_: src.modules.mlp.MLP
        in_dim: 256
        hidden_dim: 256
        out_dim: 1
