defaults:
  - regression_transfer

cls_token: false
selector:
  _target_: src.modules.vision_backbones.ImageSelector
backbone:
  _target_: src.modules.vision_backbones.EfficientNet
head:
  in_dim: 1280
