# @package _global_

defaults:
  - /loss: mse

model:
  _target_: src.models.regression_transfer.RegressionTransfer
  min_value: -inf
  max_value: inf


  compile: false

  selector:
      _target_: torch.nn.Identity

  optimizer:
    _target_: torch.optim.AdamW
    _partial_: true
    lr: 0.00715
    weight_decay: 0.001973
  lr_min: 0.000345

  head:
    _target_: src.modules.mlp.MLP
    in_dim: 1024
    hidden_dim: 256
    out_dim: 1
#  head:
#    _target_: src.modules.mlp.MLP
#    in_dim: 1024
#    hidden_dim: 1024
#    out_dim: 1
#    drop: 0.1