_target_: src.models.autoencoder.AutoEncoder

compile: true

optimizer:
  _target_: torch.optim.AdamW
  _partial_: true
  lr: 1e-3
  weight_decay: 1e-4
lr_min: 1e-6

model:
  _target_: src.modules.tag_models.TagCountAE
  embedding_file: data/tiles/embeddings.pkl
  h_dim: 256