# @package _global_
data:
  load_images: false

model:
  _target_: src.models.regression_transfer.RegressionTransfer
  min_value: -inf
  max_value: inf

  compile: false

  selector:
    _target_: torch.nn.Identity

  optimizer:
    _target_: torch.optim.AdamW
    _partial_: true
    lr: 0.00715
    weight_decay: 0.001973
  lr_min: 0.000345

#  loss:
#    _target_: torch.nn.MSELoss
    #zero_fraction: ${data.zero_fraction}

  cls_token: false
  backbone:
    _target_: torch.nn.Identity
  head:
    _target_: src.modules.tag_models.Tagformer
    embedding_file: ${paths.data_dir}/tiles/embeddings.pkl
    use_padding_mask: true
    use_proj_activation: true
    use_semantic_encoding: true
    use_positional_encoding: true
    out_dim: 1

trainer:
  accumulate_grad_batches: 4
