# https://lightning.ai/docs/pytorch/stable/api/lightning.pytorch.callbacks.ModelCheckpoint.html

save_last:
  dirpath: ${paths.output_dir}/checkpoints
  filename: "last"
  monitor: "val/loss"
  mode: "min"
  save_last: True
  save_top_k: 0
  every_n_epochs: 10 # number of epochs between checkpoints
  auto_insert_metric_name: False
  _target_: lightning.pytorch.callbacks.ModelCheckpoint
  verbose: False # verbosity mode
  save_weights_only: False # if True, then only the model’s weights will be saved
  every_n_train_steps: null # number of training steps between checkpoints
  train_time_interval: null # checkpoints are monitored at the specified time interval
  save_on_train_epoch_end: null # whether to run checkpointing at the end of the training epoch or the end of validation