# @package _global_

defaults:
  - _self_
  - data: traffic_signals # choose datamodule with `test_dataloader()` for evaluation
  - logger: tensorboard
  - trainer: gpu
  - paths: default
  - extras: default
  - hydra: default

task_name: "eval"

tags: ["eval"]

data:
  tiny: true

# passing checkpoint path is necessary for evaluation
ckpt: null
