# @package _global_

# runs with execution time profiling

defaults:
  - default

trainer:
  max_epochs: 1
  limit_train_batches: 0.01
  limit_val_batches: 0.05
  limit_test_batches: 0.05
  detect_anomaly: False
  profiler: "simple"
  #profiler: "advanced"
  #profiler: "pytorch"
