name: "geojepa_training"
tags: []
setup_command: "bash setup.sh"
command: "bash run.sh"

resources:
  docker_image: {DOCKER_IMAGE_CUDA_TOOLKIT}
  task_type: 2gpu
#  num_gpus: 1
#  num_cpus: 10
#  memory_gb: 90
#  disk_gb: 250