name: "geojepa_pretraining"
tags: []
setup_command: "bash setup.sh"
command: "bash run.sh"

project_id: playground #a project_id is needed for preemptible tier task
scheduling_options:
  tiers: preemptible
cluster_options:
   aws:
     instance_type: p4de.24xlarge # A100-80GB

resources:
  docker_image: {DOCKER_IMAGE_CUDA_TOOLKIT}
  cluster: "AWS_ALL"
  task_type: 1gpu
  timeout: 4d
#  num_gpus: 1
#  num_cpus: 12
#  memory_gb: 135
#  disk_gb: 250
